################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"
# theme
theme = "dot"
# site title
title = "Stone OpenBank"
# default language
defaultContentLanguage = "pt"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. Ex: UA-123-45

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Referência da API"
url = "referencia-da-api"
weight = 1

[[menu.main]]
name = "Guias"
url = "guias"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "Quero ser parceiro"
url = "quero-ser-parceiro"
#hasChildren = true

# exemplo de children menu
#  [[menu.main]]
#  parent = "docs"
#  name = "Installation"
#  url = "installation"
#  weight = 1

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will show your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

# languages
[languages]
    ### Portuguese Language ###
    [Languages.pt]
        languageName = "pt"
        languageCode = "pt"
        weight = 1
        # home = "Home"
        # TODO: change footer text
        copyright = "Feito com 💚 e com [Hugo](https://gohugo.io) - 2020."

        # banner
        [Languages.pt.params.banner]
            title = "Stone OpenBank"
            subtitle = "Escreva o Banco do futuro. Uma linha de código por vez."
            # TODO: add background image
            bg_image = "grid.png"
            placeholder = "Search"
        # call to action
        [Languages.pt.params.cta]
            enable = true
            # TODO: change content or disable
            title = "Não encontrou uma resposta para sua dúvida?"
            content = "Sem problemas, estamos aqui para ajudar!"
        # call to action button
        [Languages.pt.params.cta.button]
            enable = true
            # TODO: change content or disable
            label = "Entrar em contato"
            # TODO: colocar link certo para contato
            link = "https://docs.openbank.stone.com.br/discuss-new"